### ISSUE TITLE
Publishing releases

### ISSUE THREAD

**Issue by bibamba** [thomasmitchell/prism-boshrelease#1]
Hi Tom,
I hope you are doing well. My name is Bi Bamba, and I work at Stark and Wayne. I am interested with contributing and publishing prism-boshrelease. One of our customer is using it in their environments. They want to have more release of it. 

Best regards.

Bi Bamba

**Comment by thomasmitchell** [comment]
relevant repos have now been moved to github.com/cloudfoundry-community/prism and github.com/cloudfoundry-community/prism-boshrelease, so folks other than me should now have the ability to contribute.

**Comment by bibamba** [comment]
Okay. Thank you.
